### ISSUE TITLE
Getting crash while encoding provision command to wbxml

### ISSUE THREAD

**Issue by dpatel** [jasenhuang/ASWBXml-c#1]
Here is my xml 
![screen shot 2015-01-17 at 5 04 32 pm](https://cloud.githubusercontent.com/assets/2101313/5788685/eeadf4fc-9e6a-11e4-8177-051d581e7a80.png)
xml=@"<?xml version=\"1.0\"?> <!DOCTYPE ActiveSync PUBLIC \"-//MICROSOFT//DTD ActiveSync//EN\" \"http://www.microsoft.com/\"> <Provision xmlns=\"Provision:\"> <Policies> <Policy> <PolicyType>MS-WAP-Provisioning-XML</PolicyType> </Policy></Policies></Provision>";

and getting crash... Below is the log.

Printing description of this:
(std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char> > > *) this = 0x000000000000005a
(lldb) 

I hope you might help me :)

**Comment by jasenhuang** [comment]
hi dpatel, 
      I add Unit Test in ASWBXml project for encode and decode the "Provision" xml, it works well. you can update to lastest version to check it.

**Comment by dwijsoft-dipen** [comment]
Hi Jesenhuang it works fine. It was an issue from my end, i apologies for it and closed the issue.
